### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by EstianH** [crstauf/calyx#16]
On activating Calyx from the WP administration panel a blank page with an error is shown:

_**Parse error: syntax error, unexpected ';' in /usr/www/users/******/******/wp-content/themes/calyx/includes/utilities.php on line 71**_

This occurs on both the front-end and back-end as neither are accessible post activation.

**PHP Version:** 7.0
**WP Version:** 4.9.8

**Comment by crstauf** [comment]
Hey @EstianH, thanks for reporting this!

And yep, sure enough; a rogue semi-colon: https://github.com/crstauf/calyx/blob/c2d3940613bae59debfa1a07922c2b6a0660878b/includes/utilities.php#L71

Will get that fix pushed up. :)

**Comment by crstauf** [comment]
@EstianH Rogue semi-colon eliminated. :)
